version = 0.1

[default.build]
[default.build.parameters]
[dev.build]
[dev.build.parameters]
[prd.build]
[prd.build.parameters]
beta_features = true

[dev.deploy]
[dev.deploy.parameters]
stack_name = "yourcat-dev"
s3_bucket = "common-dev-sam-artifactstore"
s3_prefix = "yourcat-dev"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
parameter_overrides = [
    "EnvironmentName=dev",
    "ApiAllowOrigin=http://localhost:8080",
]
tags = "project=\"yourcat\" env=\"dev\" IaC=\"cfn\""
confirm_changeset = false

[prd.deploy]
[prd.deploy.parameters]
stack_name = "yourcat-prd"
s3_bucket = "common-prd-sam-artifactstore"
s3_prefix = "yourcat-prd"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
parameter_overrides = [
    "EnvironmentName=prd",
    "ApiAllowOrigin=https://mirumi.me",
]
tags = "project=\"yourcat\" env=\"prd\" IaC=\"cfn\""
confirm_changeset = false

[default.sync]
[default.sync.parameters]
stack_name = "yourcat-dev"
s3_bucket = "common-dev-sam-artifactstore"
s3_prefix = "yourcat-dev"
beta_features = true
watch = true
