name: deploy

on:
  push:
    branches:
      - main
      - release/prd

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - uses: aws-actions/setup-sam@v2

      - name: Sign in to AWS
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-northeast-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Decrypt secrets
        run: |
          echo "${{ secrets.GPG_PASSPHRASE }}" | sudo gpg --batch --passphrase-fd 0 --output "secret.py" --decrypt "twitter/secret.py.gpg"

      # 現状の説明：
      # Python だけ --use-container する方法がわからんので release/prd にマージはしていない。プルリクだけ Open になってる。

      - name: Build
        run: |
          pip3 install cargo-lambda
          yes | sam build --beta-features

      - name: Deploy (dev)
        if: ${{ github.ref == 'refs/heads/main' }}
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --config-env dev

      - name: Deploy (prd)
        if: ${{ github.ref == 'refs/heads/release/prd' }}
        run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --config-env prd
